#### 動態輸出

In [9]:
'%.*s' % (3, 'abcdefghijk') #一定要放'*', 由3決定輸出長度

'abc'

In [11]:
print('%5.3s' % ('abcdefghijk'))

print('%*.*s' % (5, 3, 'abcdefghijk')) #這兩個是一樣的

  abc
  abc


### %f : 浮點數

In [14]:
'%f' % (123.456789159) #python 小數位數顯示6位

'123.456789'

In [15]:
'%.3f' % (123.456789159) #往前取一位，四捨五入

'123.457'

In [17]:
'%5.3f' % (987654123.456789159) # 失效

'987654123.457'

In [19]:
'%6.3f' % (3.14159)

' 3.142'

In [20]:
'%06.3f' % (3.14159) #前面補0

'03.142'

In [22]:
'%2.3f' % (123.456789159)

'123.457'

In [24]:
print('%*.*f' % (5, 2, 3.14159))
print('%0*.*f' % (5, 2, 3.14159))

 3.14
03.14


### 2. format (新制 python3.6之後(含))

In [26]:
'{}'.format(123)

'123'

In [27]:
'{}, {}'.format(123, 456) #order

'123, 456'

In [28]:
'{1}, {0}'.format(123, 456) #index, 可以用丟位置索引直改變順序

'456, 123'

In [29]:
'{bbb}, {aaa}'.format(aaa = 123, bbb = 456) #name

'456, 123'

#### order

In [34]:
'{}, {}'.format(123, 456)

'123, 456'

In [30]:
'{:d}, {:s}'.format(123, 'abc')

'123, abc'

In [31]:
'{:.3f}, {:.3s}'.format(123.456789, 'abcdef')

'123.457, abc'

In [37]:
'{:09.3f}, {:5.3s}'.format(123.456789, 'abcdef')

'00123.457, abc  '

In [39]:
'{:09.3f}, {:>5.3s}'.format(123.456789, 'abcdef')

'00123.457,   abc'

In [42]:
'{:09.3f}, {:*^7.3s}'.format(123.456789, 'abcdef')
           # 空的用 '*' 填滿

'00123.457, **abc**'

#### index

In [35]:
'{1}, {0}'.format(123, 456) 

'456, 123'

In [33]:
'{1:.3s}, {0:.3f}'.format(123.456789, 'abcdef')

'abc, 123.457'

In [ ]:
'{1:.3s}, {0:.3f}'.format(123.456789, 'abcdef')

#### name

In [38]:
'{bbb}, {aaa}'.format(aaa = 123, bbb = 456)

'456, 123'

In [44]:
L1 = [100, 200, 300]
L2 = ['aaa', "bbb", "ccc"]

'{}, {}'.format(L1[1], L2[0])

'200, aaa'

In [47]:
d = {'abc': 123456789, 2: 'abcdef'}
# key:value
'{1:.3s}, {0:,}'.format(d['abc'], d[2])

'abc, 123,456,789'

In [48]:
a = 22
'10進制:{0:}, 16進制:{0:x}, 8進制:{0:o}, 2進制:{0:b}'.format(a)

'10進制:22, 16進制:16, 8進制:26, 2進制:10110'

In [52]:
a = 1000
print('2進制:{0:_b}'.format(a))
print('10進制:{0:_}'.format(a))

2進制:11_1110_1000
10進制:1_000


In [55]:
'{1:.{0}f}'.format(2, 123.456789) #動態輸出
# .{0}f , 索引值0是2 -> .2f

'123.46'

### 3. f-string (新制 python3.7之後(含))

In [56]:
aaa = 123
f'{aaa}'

'123'

In [57]:
aaa = 123456789
f'{aaa:,}'

'123,456,789'

In [58]:
a = 22
f'10進制:{a:}, 16進制:{a:x}, 8進制:{a:o}, 2進制:{a:b}'.format(a)

'10進制:22, 16進制:16, 8進制:26, 2進制:10110'

In [59]:
f'{9*9}'

'81'

In [61]:
import sys
f'{sys.platform}'

'win32'

# Python 容器型別

1. list 串列 `[ ]`
2. tuple 元組
3. dict 字典
4. set 集合

# Numpy 容器型別
1. array 陣列 `[ ]`

# Pandas 容器型別
1. Series 一維
2. DataFrame 二維

### 1. List 串列

In [63]:
l = [1,2,3,4,5]
l

[1, 2, 3, 4, 5]

In [65]:
l = [1,2,3.14,'abc', True, b'1101'] #可以擺放異質資料
l

[1, 2, 3.14, 'abc', True, b'1101']

In [66]:
l[2]

3.14

In [68]:
l[0] = [123]
l # 串列裡可以放串列

[[123], 2, 3.14, 'abc', True, b'1101']

In [70]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
print(a)

[1 2 3 4 5 6 7 8 9]


In [71]:
type(a)

numpy.ndarray

In [77]:
print('形狀:', a.shape)
print('數量:', a.size)
print('維度:', a.ndim)
print('資料型別:', a.dtype)
print('記憶體位置:', a.data)

形狀: (9,)
數量: 9
維度: 1
資料型別: int32
記憶體位置: <memory at 0x000002A09FD5C880>


In [75]:
import numpy as np
b = np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [78]:
print('形狀:', b.shape)
print('數量:', b.size)
print('維度:', b.ndim)
print('資料型別:', b.dtype)
print('記憶體位置:', b.data)

形狀: (2, 2)
數量: 4
維度: 2
資料型別: int32
記憶體位置: <memory at 0x000002A09F1C79F0>


### array與list最大差異

|array|list|
| :---: | :---: |
|僅可放置**單一**種資料型別的資料|可放置**多種**資料型別的資料|
|同質資料|異質資料|
||int, bool, float, str...|

In [86]:
l = [1,2,3.14,'abc', True, b'1101'] #可以擺放異質資料
l

[1, 2, 3.14, 'abc', True, b'1101']

In [81]:
np.array([1,2,3.14,'abc', True, b'1101']) #不應該更改的東西被強制轉換，array無法放異質資料

array(['1', '2', '3.14', 'abc', 'True', '1101'], dtype='<U32')

In [84]:
import numpy as np
a = np.random.randint(101, size = 5)
a

array([35, 45, 90, 62,  9])

In [85]:
a.dtype

dtype('int32')

In [90]:
a[2] = 3.14159
a

array([35, 45,  3, 62,  9])

In [91]:
a[2] = 'abc'
a

ValueError: invalid literal for int() with base 10: 'abc'

In [92]:
l = [1,2,3.14,'abc', True, b'1101'] #可以擺放異質資料
l

[1, 2, 3.14, 'abc', True, b'1101']

In [94]:
import numpy as np
np.random.seed(5) # 亂數產生 隨機種子
l = list(np.random.randint(101, size = 5)) # 將陣列強制轉型成串列
l 

[99, 78, 61, 16, 73]

In [102]:
max(l), min(l), sum(l), len(l), sum(l)/len(l) #python內建函數

(99, 16, 327, 5, 65.4)

In [103]:
sorted(l) #遞增排序

[16, 61, 73, 78, 99]

In [104]:
l # 用內建函數功能，不會影響原本順序

[99, 78, 61, 16, 73]

In [105]:
l.sort() #用list排序會改變原本順序，遞增排序
l

[16, 61, 73, 78, 99]

In [106]:
l.sort(reverse = True) #用list排序會改變原本順序，遞減排序
l

[99, 78, 73, 61, 16]

In [109]:
import numpy as np
np.random.seed(5) 
l1 = list(np.random.randint(101, size = 5)) 
l1 
l2 = list(np.random.randint(101, size = 5)) 
l2 

print(l1, l2)

[99, 78, 61, 16, 73] [8, 100, 62, 27, 30]


In [110]:
l1 + l2

[99, 78, 61, 16, 73, 8, 100, 62, 27, 30]

In [111]:
l1 #合併不影響原本值

[99, 78, 61, 16, 73]

In [114]:
l1.extend(l2) # extend會改變資料，僅存放物件元素
print(l1)
print(l2)

[99, 78, 61, 16, 73, 8, 100, 62, 27, 30, 8, 100, 62, 27, 30, 8, 100, 62, 27, 30]
[8, 100, 62, 27, 30]


In [122]:
import numpy as np
np.random.seed(5) 
l1 = list(np.random.randint(101, size = 5)) 
l1 
np.random.seed(7) 
l2 = list(np.random.randint(101, size = 5)) 
l2 

[47, 68, 25, 67, 83]

In [121]:
l1.append(l2) # append丟整個物件資料
l1

[99, 78, 61, 16, 73, [47, 68, 25, 67, 83]]

In [126]:
l1 = l1.append(l2) # append無回傳資料，所以不用複寫 -> 'l1 ='
l1

AttributeError: 'NoneType' object has no attribute 'append'

In [143]:
import numpy as np
np.random.seed(5) 
l1 = list(np.random.randint(101, size = 5)) 
np.random.seed(7) 
l2 = list(np.random.randint(101, size = 5)) 

In [138]:
l1

[99, 78, 61, 16, 73]

In [139]:
l1.pop() # 取最後一個值

73

In [140]:
l1

[99, 78, 61, 16]

In [141]:
l1.append(73) # 加入值
l1

[99, 78, 61, 16, 73]

In [142]:
l1.pop(2) # 可以針對要的值取出
l1 

[99, 78, 16, 73]

In [148]:
import numpy as np
np.random.seed(5) 
l1 = list(np.random.randint(101, size = 5)) 
np.random.seed(7) 
l2 = list(np.random.randint(101, size = 5)) 

In [149]:
l1

[99, 78, 61, 16, 73]

In [150]:
l1.remove(61) # 第一次
l1

[99, 78, 16, 73]

In [151]:
l1.remove(61) # 重複做第二次，針對list有存在的資料進行刪除，不存在的資料無法刪
l1

ValueError: list.remove(x): x not in list

In [152]:
l1.clear()

In [153]:
l1

[]

In [7]:
import numpy as np
np.random.seed(5) 
l1 = list(np.random.randint(101, size = 5)) 
np.random.seed(7) 
l2 = list(np.random.randint(101, size = 5)) 

In [8]:
l1.count(61)

1

In [9]:
l1.index(61)

2

### 2. tuple 元組

- 一旦建立後，就無法修改
- 符號為 `（)`

In [10]:
t = (1,2,3.14,'abc', True, b'1101')
t

(1, 2, 3.14, 'abc', True, b'1101')

In [155]:
t[2]

3.14

In [156]:
t[2] = 123.456

TypeError: 'tuple' object does not support item assignment

In [1]:
t.pop()

NameError: name 't' is not defined

In [2]:
t.remove()

NameError: name 't' is not defined

In [5]:
t.count(3.14)

1

In [12]:
import numpy as np
np.random.seed(5) 
l1 = tuple(np.random.randint(101, size = 5)) 
type(l1)

tuple

### 3. dict字典

- 格式1 `{key:value}`
- 格式2 `dict(key = value)`
- key是唯一值
- value可重複
- 使用dict(key = value)建立字典，key不能使用數字，需使用`字母`, `_`
- key不能更改

In [14]:
d = {'a':1, 'b':2}
d

{'a': 1, 'b': 2}

In [15]:
d = {1:2, 3:4, 5:6}
d

{1: 2, 3: 4, 5: 6}

In [16]:
d = dict(a = 1, b = 2)
d

{'a': 1, 'b': 2}

In [17]:
d = dict(1 = 2, 3 = 4, 5 = 6)
d

SyntaxError: expression cannot contain assignment, perhaps you meant "=="? (389718835.py, line 1)

In [18]:
d = dict(_ = 1)
d

{'_': 1}

#### 取值

In [19]:
d = {'a':1, 'b':2}
d

{'a': 1, 'b': 2}

In [20]:
d['a']

1

In [23]:
d.keys()

dict_keys(['a', 'b', 'c'])

In [24]:
d.values()

dict_values([3, 2, 5])

In [25]:
d.items()

dict_items([('a', 3), ('b', 2), ('c', 5)])

#### 改值

In [21]:
d['a'] = 3
d

{'a': 3, 'b': 2}

#### 新增

In [22]:
d['c'] = 5
d

{'a': 3, 'b': 2, 'c': 5}

#### 查詢

In [26]:
d['c']

5

In [27]:
d['f'] #不存在

KeyError: 'f'

In [29]:
d.get('f', 404) #查找是否存在

404

#### 加參數

In [32]:
d['d'] = 100
d['e'] = 50
d['f'] = 9
d

{'a': 3, 'b': 2, 'c': 5, 'd': 100, 'e': 50, 'f': 9}

In [33]:
d.update({'g': 7, 'h': 3.14, "i":'abc'})
d

{'a': 3,
 'b': 2,
 'c': 5,
 'd': 100,
 'e': 50,
 'f': 9,
 'g': 7,
 'h': 3.14,
 'i': 'abc'}

#### 刪除

In [35]:
del d['c']
d

{'a': 3, 'b': 2, 'd': 100, 'e': 50, 'f': 9, 'g': 7, 'h': 3.14, 'i': 'abc'}

In [1]:
import numpy as np
np.random.seed(5) 
l1 = list(np.random.randint(101, size = 5)) 
np.random.seed(7) 
l2 = list(np.random.randint(101, size = 5)) 

In [37]:
l1,l2

([99, 78, 61, 16, 73], [47, 68, 25, 67, 83])

In [38]:
dict(zip(l1,l2))

{99: 47, 78: 68, 61: 25, 16: 67, 73: 83}

### 迴圈 for
- 同一件事重複做

```Python
for 變數 in 序列資料:
    執行重複的事
```

In [39]:
for i in [1,2,3,4,5]:
    print(i)

1
2
3
4
5


In [41]:
for k in d.keys():
    print(k)

a
b
d
e
f
g
h
i


In [44]:
for k in d.keys():
    print(k,d[k])

a 3
b 2
d 100
e 50
f 9
g 7
h 3.14
i abc


In [45]:
for k, v in zip(d.keys(), d.values()):
    print(k, v)

a 3
b 2
d 100
e 50
f 9
g 7
h 3.14
i abc


In [46]:
for value in zip(d.keys(), d.values()):
    print(value)

('a', 3)
('b', 2)
('d', 100)
('e', 50)
('f', 9)
('g', 7)
('h', 3.14)
('i', 'abc')


In [47]:
for value in zip(d.keys(), d.values()):
    print(value[0], value[1])

a 3
b 2
d 100
e 50
f 9
g 7
h 3.14
i abc


In [48]:
for value in d.items():
    print(value)

('a', 3)
('b', 2)
('d', 100)
('e', 50)
('f', 9)
('g', 7)
('h', 3.14)
('i', 'abc')


In [50]:
for k, v in d.items():
    print(k, v)

a 3
b 2
d 100
e 50
f 9
g 7
h 3.14
i abc


### 亂數用法
1. np.random.randint(start, end, size) 
2. np.random.randint(end, size) 
3. np.random.randint(end) 

In [54]:
import numpy as np
#np.random.seed(5) 
np.random.randint(62, 101)

78

In [63]:
size = 10
d = {}
for i in range(size):
    d[chr(np.random.randint(65, 91))] = np.random.randint(65, 91) # 這個key有可會重複，就會少值
d 

{'G': 80, 'P': 68, 'R': 84, 'A': 73, 'N': 83, 'S': 80, 'T': 87, 'L': 85}

### range()用法

1. range(end)
2. range(start, end) 
3. range(start, end, step) 

---

- step預設為1，且可為正(遞增)可為負(遞減)

In [64]:
range(10) #無法執行

range(0, 10)

In [65]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [68]:
a,*b = range(10)
a

0

In [67]:
b

[1, 2, 3, 4, 5, 6, 7, 8, 9]

### numpy arange()用法

1. range(end)
2. range(start, end) 
3. range(start, end, step) 

---

- step預設為1，且可為正(遞增)可為負(遞減)

In [70]:
import numpy as np
np.arange(10)  #可以直接執行

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### range()與np.arange()差異

||range()|np.arange()|
| :---:| :---: | :---: |
|搭配list|需要|X|
|產生內容|整數|整數、浮點數|

In [73]:
list(range(1, 10, 0.5))

TypeError: 'float' object cannot be interpreted as an integer

In [72]:
import numpy as np
np.arange(1, 10, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

**如果把原始函數拿來當變數，會改變它的型態**

In [74]:
sum = 0

for i in range(11):
    sum = sum + i
sum  

55

In [2]:
l1

[99, 78, 61, 16, 73]

In [3]:
sum(l1)

327

### set集合

1. 建立方式1 `s = {}`
2. 建立方式2 `s = set{}`
3. 空集合 `set{}`
4. 集合內的元素皆唯一
5. 可存放異質資料

In [1]:
s = {1,2,5,1,3,2,8,8}
s

{1, 2, 3, 5, 8}

In [2]:
s = {1, 2, 3.14, "abc", True, b'1101'}
s

{1, 2, 3.14, 'abc', b'1101'}

In [3]:
s[2]

TypeError: 'set' object is not subscriptable

In [3]:
s.add('123abc') #自動排序上去
s

{1, '123abc', 2, 3.14, 'abc', b'1101'}

In [4]:
s

{1, '123abc', 2, 3.14, 'abc', b'1101'}

##### 沒copy，兩個名子共用一資料

##### .copy()，兩個名子有各自的資料

In [5]:
s1 = s #這個並不是新建s1容器，而是s更名叫s1
s1

{1, '123abc', 2, 3.14, 'abc', b'1101'}

In [6]:
s1.pop() # pop隨機取出一個

1

In [7]:
s1

{'123abc', 2, 3.14, 'abc', b'1101'}

In [20]:
s

{'123abc', 2, 3.14, 'abc', b'1101'}

In [21]:
s2 = s.copy()

In [24]:
s2.pop()

2

In [25]:
s2

{'123abc', 3.14, 'abc', b'1101'}

In [26]:
s

{'123abc', 2, 3.14, 'abc', b'1101'}

### 迴圈 for
- 同一件事重複做

```Python
for 變數 in 序列資料:
    執行重複的事
```

In [27]:
for i in range(1, 10, 2):
    print(i)

1
3
5
7
9


In [31]:
for l in range(10, 1, -2):
    print(l)

10
8
6
4
2


##### 100的因數

In [32]:
10//3 #取商數整數

3

In [33]:
10/3 #取商數

3.3333333333333335

In [34]:
10%3 #取餘數

1

In [9]:
for i in range(1,101):
    if 100%i == 0:
        print(i)
        times = 0
        for j in range(1, i+1):
            if i%j == 0:
                times = times + 1
            
        if times == 2:
            print(i, '為質因數')

1
2
2 為質因數
4
5
5 為質因數
10
20
25
50
100


### 99乘法表

In [25]:
for i in range(1,10):
    for j in range(1, 6):
        #print(j, "*", i, "=", i*j, end = "\t")
        #print(f"{j} * {i} = {i*j}", end = "\t")
        #print('%d * %d = %d' % (j, i, j*i), end = "\t")
        print("{} * {} = {}".format(j, i, j*i), end = "\t")
    print()

1 * 1 = 1	2 * 1 = 2	3 * 1 = 3	4 * 1 = 4	5 * 1 = 5	
1 * 2 = 2	2 * 2 = 4	3 * 2 = 6	4 * 2 = 8	5 * 2 = 10	
1 * 3 = 3	2 * 3 = 6	3 * 3 = 9	4 * 3 = 12	5 * 3 = 15	
1 * 4 = 4	2 * 4 = 8	3 * 4 = 12	4 * 4 = 16	5 * 4 = 20	
1 * 5 = 5	2 * 5 = 10	3 * 5 = 15	4 * 5 = 20	5 * 5 = 25	
1 * 6 = 6	2 * 6 = 12	3 * 6 = 18	4 * 6 = 24	5 * 6 = 30	
1 * 7 = 7	2 * 7 = 14	3 * 7 = 21	4 * 7 = 28	5 * 7 = 35	
1 * 8 = 8	2 * 8 = 16	3 * 8 = 24	4 * 8 = 32	5 * 8 = 40	
1 * 9 = 9	2 * 9 = 18	3 * 9 = 27	4 * 9 = 36	5 * 9 = 45	


### 邏輯控制 -> if

```Python
#單選
if 條件式:
    程式1
    
#二擇一
if 條件式1:
    程式1
else:
    程式2
    
#多擇一
if 條件式1:
    程式1
elif 條件式2:
    程式2
else:
    程式3
```

In [8]:
a = 10
if a < 5:
    print("a小於5")
elif a == 5:
    print("a等於5")
else:
    print("a大於5")

a大於5


### 運算子

1. 邏輯運算子 `and` -> `*`, `or` -> `+`, `not` -> `1-a`
2. 算數運算子 `+` `-` `*` `/` `%` `//`
3. 設定運算子 `+=` `-=` `*=` `/=` `%=` `//=`
4. 比較運算子 `==` `>` `>=` `<` `<=` `!=`
5. 成員運算子 `in`
6. 位元運算子 `&` `|` `~` `<<` `>>`

#### 邏輯運算子

In [30]:
a = 5 
b = 2
a > 3 and b < 3

True

In [31]:
a = 5 
b = 2
a > 3 or b < 2

True

In [32]:
not a > 3

False

#### 位元運算子

[二補數](https://zh.wikipedia.org/wiki/%E4%BA%8C%E8%A3%9C%E6%95%B8)

In [33]:
7 & 3

3

In [34]:
7 | 3

7

In [35]:
~1

-2

In [36]:
5 << 2

20

In [37]:
5 >> 2

1

#### 設定運算子

In [40]:
i = 0
i += 1
i

1

In [41]:
i = 0
i -= 1
i

-1

In [42]:
i = 0
i *= 1
i

0

In [43]:
i = 0
i /= 1
i

0.0

#### 比較運算子

In [44]:
a = 5
b = 3
a > b

True

In [45]:
a < b

False

In [ ]:
a = b #賦值
a == b #左邊是否等於右邊

In [47]:
a = 5
b = 2
a => b

SyntaxError: invalid syntax (1077485263.py, line 3)

#### 成員運算子

In [48]:
import numpy as np
np.random.seed(5) 
l1 = list(np.random.randint(101, size = 5)) 
l1

[99, 78, 61, 16, 73]

In [49]:
5 in l1

False

In [50]:
99 in l1

True

In [51]:
d = {'a':1, 'b':2}
d.update({'g': 7, 'h': 3.14, "i":'abc'})
d

{'a': 1, 'b': 2, 'g': 7, 'h': 3.14, 'i': 'abc'}

In [52]:
d.keys()

dict_keys(['a', 'b', 'g', 'h', 'i'])

In [53]:
d.values()

dict_values([1, 2, 7, 3.14, 'abc'])

In [54]:
2 in d

False

In [56]:
'b' in d #比對到key，因為value是由key帶出來的

True